apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-web
  labels:
    app: status-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: status-web
  template:
    metadata:
      labels:
        app: status-web
    spec:
      containers:
      - name: status-web
        # If you would like to give a try by using the image that store from IBM Cloud Container Registry
        # just un-comment the following line and update it (replace $YOURNAME) to correct URL to retrive the image.
        # image: us.icr.io/$YOURNAME-iks101/$YOURNAME-status-page:1
        # default, use image stored on dockerHub (public) 
        image: nuttapwong/status-page:1
        imagePullPolicy: Always
        env:
          - name: REDIS_HOST
            value: "redis-leader"
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: status-web
  labels:
    app: status-web
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    name: status-web
    protocol: TCP
  selector:
    app: status-web
